Homework
htmlacademy-htmlcss/1815029-sedona-31 pull request #4
Opened 2021-05-30 05:56 UTC by NugmanovSalavat

2021-05-30 17:41 UTC, andreysgra requested changes

2021-05-30 17:41 UTC, andreysgra commented on index.html
> +      </nav>
Логотип не является пунктом меню. Об этом говорит [этот пункт](https://up.htmlacademy.ru/htmlcss/31/project/sedona#sedona-3-2) ТЗ, но это часть навигации, поэтому из списка меню его выносим.

Разметка должна быть такой:
```
<nav>
  <a href="index.html"><img src="https://via.placeholder.com/150x100" alt="catalog"></a>
  <ul>
    <li><a href="blank.html">Информация</a></li>
    <li><a href="blank.html">Фото и видео</a></li>
    <li><a href="blank.html">Карта штата</a></li>
    <li><a href="catalog.html">Гостиницы</a></li>
  </ul>
</nav>
```
Пункт меню "Гостиницы" - ссылка на страницу каталога.

2021-05-30 17:41 UTC, andreysgra commented on index.html
> +                        <h3>Сувениры</h3>
В этом блоке логичнее использовать заголовки `h4`, так как выше есть `h3`.

2021-05-30 17:41 UTC, andreysgra commented on index.html
> +                        <img src="img/icon-1.svg" alt="icon_1">
Эти иконки - изображения декоративные и можно не добавлять их в разметку с помощью `img` (добавим позже с помощью CSS).
![image](https://user-images.githubusercontent.com/17790771/120114060-0b0b4b00-c186-11eb-820c-fa87fbd371f2.png)

2021-05-30 17:41 UTC, andreysgra commented on index.html
> +    </section>
Нужно разметить данный блок:
![image](https://user-images.githubusercontent.com/17790771/120114126-5de50280-c186-11eb-9ac2-5702972edc6a.png)
Сразу после кнопки "Поиск гостиницы в Седоне". Это форма.

2021-05-30 17:41 UTC, andreysgra commented on index.html
> +      </ul>
Данные элементы не нужно объединять в один список. `ul` нужен только для ссылок на соцсети.

2021-05-30 17:41 UTC, andreysgra commented on index.html
> +    </footer>
В подвале сайта есть ещё такой элемент. У вас он пропущен. То, что обвёл красным цветом - ссылка на лендинг интенсива. Об этом написано в [данном пункте](https://up.htmlacademy.ru/htmlcss/31/project/sedona#sedona-3-8) ТЗ.
![image](https://user-images.githubusercontent.com/17790771/120114298-32164c80-c187-11eb-9711-23d1530b9035.png)

2021-06-01 12:43 UTC, NugmanovSalavat commented
Ошибки исправлены

2021-06-01 12:44 UTC, NugmanovSalavat reviewed
1

2021-06-01 12:46 UTC, NugmanovSalavat reviewed
2

2021-06-01 12:47 UTC, NugmanovSalavat reviewed
3

2021-06-01 17:44 UTC, andreysgra approved these changes

2021-06-01 17:44 UTC, andreysgra commented on index.html
> +      <img src="https://via.placeholder.com/150x100" alt="website.by">
**website by** - ну это текст.

2021-06-01 17:44 UTC, merged